##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

CFLAGS = 	-W -Wall -Wextra

all:
		make -C ./antman
		make -C ./giantman

antman:
		make -C ./antman

giantman:
		make -C ./giantman

clean:
		make clean -C ./antman
		make clean -C ./giantman

fclean:
		make fclean -C ./antman
		make fclean -C ./giantman

re:
		make re -C ./antman
		make re -C ./giantman

z:
		make z -C ./antman
		make z -C ./giantman

.PHONY: all antman giantman clean fclean re z
