##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

CFLAGS = 	-W -Wall -Wextra

all:
		make -C ./generator
		make -C ./solver

generator:
		make -C ./generator

solver:
		make -C ./solver

clean:
		make clean -C ./generator
		make clean -C ./solver

fclean:
		make fclean -C ./generator
		make fclean -C ./solver

re:
		make re -C ./generator
		make re -C ./solver

z:
		make z -C ./generator
		make z -C ./solver

.PHONY: all generator solver clean fclean re z
